import os

FASTAPI_SECURE_TEMPLATE = """from fastapi import FastAPI, Depends, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import OAuth2PasswordBearer
from starlette.middleware.base import BaseHTTPMiddleware
from pydantic import BaseModel, EmailStr, Field
import uvicorn
import secrets
import hashlib
import time

app = FastAPI(
    title="Secured Service Boilerplate 2026",
    docs_url="/api/docs",
    redoc_url=None
)

# 1. CORS Hardening - Strict Whitelist (Avoid wildcard '*')
ALLOWED_ORIGINS = [
    "https://trustedapp.com",
    "https://api.trustedapp.com"
]
app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "DELETE"],
    allow_headers=["Authorization", "Content-Type"],
)

# 2. Security Headers Middleware (OWASP Secure by Design)
class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request, call_next):
        response = await call_next(request)
        response.headers["X-Frame-Options"] = "DENY"
        response.headers["X-Content-Type-Options"] = "nosniff"
        response.headers["X-XSS-Protection"] = "1; mode=block"
        response.headers["Strict-Transport-Security"] = (
            "max-age=63072000; includeSubDomains; preload"
        )
        response.headers["Content-Security-Policy"] = (
            "default-src 'self'; frame-ancestors 'none';"
        )
        response.headers["Referrer-Policy"] = "no-referrer"
        return response

app.add_middleware(SecurityHeadersMiddleware)

# 3. Simple Rate Limiter Middleware
class RateLimiterMiddleware(BaseHTTPMiddleware):
    def __init__(self, app, limit: int = 100, window: int = 60):
        super().__init__(app)
        self.limit = limit
        self.window = window
        self.clients = {}  # In-memory rate tracker (Use Redis in production)

    async def dispatch(self, request, call_next):
        client_ip = request.client.host
        now = time.time()

        # Clean expired slots
        self.clients = {
            ip: times
            for ip, times in self.clients.items()
            if times and times[-1] > now - self.window
        }

        client_history = self.clients.get(client_ip, [])
        client_history = [t for t in client_history if t > now - self.window]

        if len(client_history) >= self.limit:
            raise HTTPException(
                status_code=status.HTTP_429_TOO_MANY_REQUESTS,
                detail="Rate limit exceeded. Try again later."
            )

        client_history.append(now)
        self.clients[client_ip] = client_history
        return await call_next(request)

app.add_middleware(RateLimiterMiddleware, limit=60, window=60)

# 4. Input Validation & Sanitization (XSS prevention)
class UserRegistration(BaseModel):
    email: EmailStr
    password: str = Field(
        ...,
        min_length=12,
        max_length=128,
        description="Strong password policy enforced"
    )
    username: str = Field(..., min_length=3, max_length=30)

    # Sanitize input on validation
    def sanitize(self) -> "UserRegistration":
        self.username = self.username.replace("<", "&lt;").replace(">", "&gt;")
        return self

# 5. Cryptographically Secure Token Helper
def generate_secure_token(length: int = 32) -> str:
    return secrets.token_hex(length)

@app.get("/")
def read_root():
    return {"message": "Service is running securely."}

@app.post("/register")
def register_user(user: UserRegistration):
    sanitized_user = user.sanitize()
    # In production, salt and hash the password using argon2-cffi or bcrypt
    # Example using SHA-256 with random salt (minimum requirement)
    salt = secrets.token_hex(16)
    hashed_pwd = hashlib.pbkdf2_hmac(
        'sha256',
        sanitized_user.password.encode('utf-8'),
        salt.encode('utf-8'),
        100000
    ).hex()

    return {
        "status": "user_registered",
        "username": sanitized_user.username,
        "token": generate_secure_token()
    }

if __name__ == "__main__":
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=True)
"""


class SecurityTemplateGenerator:
    @staticmethod
    def generate_boilerplate(output_dir: str) -> str:
        os.makedirs(output_dir, exist_ok=True)
        main_file = os.path.join(output_dir, "main.py")
        readme_file = os.path.join(output_dir, "README.md")
        requirements_file = os.path.join(output_dir, "requirements.txt")

        # Write Main File
        with open(main_file, "w", encoding="utf-8") as f:
            f.write(FASTAPI_SECURE_TEMPLATE.strip())

        # Write Readme File
        with open(readme_file, "w", encoding="utf-8") as f:
            f.write(
                "# Hardened FastAPI Service Boilerplate\n\n"
                "Generated by SecureForge 2026. This template includes:\n"
                "- **OWASP Security Headers**: X-Frame-Options, HSTS, CSP, Referrer Policy.\n"
                "- **Strict CORS Middleware**: Restricts external access to custom endpoints.\n"
                "- **Rate Limiting**: Stops DDoS/brute force attacks on HTTP routes.\n"
                "- **Input Sanitization**: Filters markup elements (`<`, `>`) to prevent XSS.\n"
                "- **Secure Hashing**: Standard password hashing utilizing pbkdf2_hmac SHA-256.\n"
            )

        # Write Requirements File
        with open(requirements_file, "w", encoding="utf-8") as f:
            f.write("fastapi>=0.110.0\n" "uvicorn>=0.28.0\n" "pydantic[email]>=2.6.0\n")

        return f"Successfully generated secure boilerplate at {output_dir}"
