class STRIDEThreatModeler:
    @staticmethod
    def generate_stride_model(app_type: str) -> str:
        threats = {
            "Spoofing": {
                "threat": "Adversary acts as a legitimate user or service.",
                "mitigation": (
                    "Enforce strong authentication, Multi-Factor Authentication (MFA), "
                    "and verify API keys using cryptographically secure tokens."
                ),
            },
            "Tampering": {
                "threat": (
                    "Adversary modifies requests, configuration, or database entries."
                ),
                "mitigation": (
                    "Enforce request validation schemas (Pydantic), validate database "
                    "parameters, and use message signing (HMAC) for external "
                    "communications."
                ),
            },
            "Repudiation": {
                "threat": (
                    "Adversary performs an action and denies it due to lack of audit trail."
                ),
                "mitigation": (
                    "Implement structured log systems (using correlation IDs) and forward "
                    "records to external read-only collectors (SIEM)."
                ),
            },
            "Information Disclosure": {
                "threat": (
                    "Adversary views sensitive data (passwords, tokens, customer details)."
                ),
                "mitigation": (
                    "Encrypt data at rest (AES-256) and transit (TLS 1.3), disable "
                    "detailed stack traces in production API error messages, and scan "
                    "for secrets."
                ),
            },
            "Denial of Service": {
                "threat": (
                    "Adversary exhausts system resources, making it unavailable to users."
                ),
                "mitigation": (
                    "Implement rate limiting middleware, deploy behind load "
                    "balancers/CDNs, and set strict memory/process limits."
                ),
            },
            "Elevation of Privilege": {
                "threat": "Adversary gains unauthorized access to admin/privileged routes.",
                "mitigation": (
                    "Implement Role-Based Access Control (RBAC), enforce Least Privilege "
                    "access policies, and validate session scopes on every request."
                ),
            },
        }

        md = f"# STRIDE Threat Model - {app_type.upper()} Application\n\n"
        md += (
            "Generated by SecureForge 2026. Evaluating architectural risks for "
            f"app type: `{app_type}`.\n\n"
        )
        md += "| Category | Architectural Threat | Mitigations / Countermeasures |\n"
        md += "|---|---|---|\n"
        for category, info in threats.items():
            md += f"| **{category}** | {info['threat']} | {info['mitigation']} |\n"

        md += "\n## Security Recommendation Checklist (2026)\n"
        md += (
            "1. [ ] Check CORS settings to ensure no wildcard origins `*` "
            "are allowed on routes exposing sensitive data.\n"
        )
        md += (
            "2. [ ] Validate all inputs against schema boundaries to prevent "
            "cross-site scripting (XSS) and SQL Injection.\n"
        )
        md += (
            "3. [ ] Store secrets and passwords using Argon2 or PBKDF2; do "
            "not hardcode passwords or tokens in code repositories.\n"
        )
        md += (
            "4. [ ] Run automated vulnerability tests during CI/CD to locate "
            "expired dependencies.\n"
        )

        return md
